## 安裝 Python

## anaconda 下載 :
> Windows : https://www.anaconda.com/products/individual#windows<br>
> macOS : https://www.anaconda.com/products/individual#macos

### Jupyter 快捷鍵
> * shift-enter: 跑程式
> * A : 上面增加一格
> * B : 下面增加一格
> * C : 複製 (crtl + C)
> * V : 貼上 (crtl + V)
> * Z : 復原 (crtl + Z)
> * X : 剪下 (crtl + X)
> * shift-up & shift-down: 多個block選取
> * M : markdown抄筆記
> * shift + tab : param instruction
> * tab : functions instruction

### 在 (命令提示字元 `系統管理員`) 身分下打 pip install ....... 指令( `灌程式` )
>### install packages
> * pip install numpy
> * pip install matplotlib
> * pip install opencv-python
> * pip install opencv-contrib-python
> * pip install scikit-learn
> * pip install scikit-image
> * pip install scipy
> * pip install imutils
> * pip install pytesseract

<div style="page-break-after: always"></div>

> * Windows OS :
>> pip install dlib<br>
>> or (pip install "C:\Users\User\Desktop\OpenCV\install\dlib-19.22.99-cp39-cp39-win_amd64.whl")

> * IOS :
>> pip install cmake<br>
>> pip install dlib

## 先看一段影片

In [55]:
%%HTML
<iframe width="640" height="480" 
src="https://www.youtube.com/embed/Fszu0L1JtqM?si=BbbCZv7ZdhY62lj1" 
title="YouTube video player" frameborder="0" 
allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
allowfullscreen></iframe>

# https://www.youtube.com/watch?v=Fszu0L1JtqM

><img src="../assets/images/basic/pythonLogo.png"  style='width:90%'></img>
### 程式語言的成長趨勢
><img src="../assets/images/basic/PythonTrend.png"  style='width:90%'>

<div style="page-break-after: always"></div>

### Top Python IDEs for Data Science in 2019
><img src="../assets/images/basic/mostIde.jpg"  style='width:90%'>

## 0-3, Python 特色
> * 物件導向式語言架構(Object-Oriented Program Language)
> * 直譯式, 又稱作腳本語言(Scripting language)
> * 省略變數類型宣告動作
> * 自動化的記憶體管理
> * 內建許多高階實用的資料型態, 提供許多標準函式庫及第三方套件(package)
> * 跨平台與圖形介面延伸, 能與其他語言結合
> * 優雅簡潔，易學易用

### Python3.X
> * 現在進行式同時也是未來趨勢
> * 活絡發展中
> * 對初學者較友善

### jupyter try (網路版本)
> https://jupyter.org/try
---

# Mod_01_Python簡介

In [56]:
import sys
sys.version

'3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]'

## check numpy, pandas & matplotlib

In [57]:
import cv2
import numpy as np
import dlib
import sys
import matplotlib
from matplotlib import pyplot as plt
import skimage
import sklearn
print(f'python ver.\t: {sys.version}\n\n'
      f'cv2 ver.\t: {cv2.__version__}\n\t\t: {cv2.__file__}\n\n'
      f'numpy ver.\t: {np.__version__}\n\t\t: {np.__file__}\n\n'
      f'matplotlib ver.\t: {matplotlib.__version__}\n\t\t: {matplotlib.__file__}\n\n'
      f'dlib ver.\t: {dlib.__version__}\n\t\t: {dlib.__file__}\n\n'
      f'skimage ver.\t: {skimage.__version__}\n\t\t:  {skimage.__file__}\n\n'
      f'sklearn ver.\t: {sklearn.__version__}\n\t\t:  {sklearn.__file__}\n\n')

python ver.	: 3.10.12 (main, Aug 15 2025, 14:32:43) [GCC 11.4.0]

cv2 ver.	: 4.12.0
		: /home/sunny/python_workstation/github/OpenCV-tools-image-process/.venv/lib/python3.10/site-packages/cv2/__init__.py

numpy ver.	: 2.2.6
		: /home/sunny/python_workstation/github/OpenCV-tools-image-process/.venv/lib/python3.10/site-packages/numpy/__init__.py

matplotlib ver.	: 3.10.7
		: /home/sunny/python_workstation/github/OpenCV-tools-image-process/.venv/lib/python3.10/site-packages/matplotlib/__init__.py

dlib ver.	: 20.0.0
		: /home/sunny/python_workstation/github/OpenCV-tools-image-process/.venv/lib/python3.10/site-packages/dlib/__init__.py

skimage ver.	: 0.25.2
		:  /home/sunny/python_workstation/github/OpenCV-tools-image-process/.venv/lib/python3.10/site-packages/skimage/__init__.py

sklearn ver.	: 1.7.2
		:  /home/sunny/python_workstation/github/OpenCV-tools-image-process/.venv/lib/python3.10/site-packages/sklearn/__init__.py




## 1-1 on-line help : shift + tab

In [58]:
help(print)  # shift + tab,  see whatever you want to check.  change 'len' in quotation.

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [59]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [60]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [61]:
print(50)

50


In [62]:
name = 'John'
name

'John'

In [63]:
miles = 477.5
miles

477.5

In [64]:
a, b, c = 1, 2., 'John'
print(a, b, c)
a, b, c  # tuple

1 2.0 John


(1, 2.0, 'John')

In [65]:
print(+7); print(++7)
print(12+34)
print(9**2)
print(9/2)
print(9//2)    # 整數除法
print(-9//2)   # ??? what happen??  地板式整除

7
7
46
81
4.5
4
-5


In [66]:
print('17*6\t=', 17*6)
print()        # 下一行
print('17*6\t=', 17*6, '\t17%6 = ', 17%6)

17*6	= 102

17*6	= 102 	17%6 =  5


In [67]:
a = 5; b = 3; a = a/b
a

1.6666666666666667

In [68]:
a = 5; b = 2
a = a + b   #a += b
a

7

In [69]:
a=5; b=2
a, b = b, a
a, b    

(2, 5)

## 1-2 Comparison Operators

In [70]:
a = 5;  b = 3

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

False
True
True
False
True
False


In [71]:
x = 2
print('x == 2\t:', x == 2)
print('x != 2\t:', x != 2)
print('x < 5\t:', x < 5)
print('x > 2\t:', x > 2)
print('x <= 2\t:', x <= 2)
print('x >= 2\t:', x >= 2)

x == 2	: True
x != 2	: False
x < 5	: True
x > 2	: False
x <= 2	: True
x >= 2	: True


## 1-3 Assignment Operators

In [72]:
a = 5

a = a + 3; print(a)  # a+=3
a = a - 5; print(a)  # a-=3
a = a * 2; print(a)  # a*=3
a = a / 2; print(a)  # a/=3

8
3
6
3.0


## 1-4 Logical Operators

> Python no Boolean.  It is `整數的子型態` (subtype of integers)<br>
> True = 1, False = 0

>### 4-3 真值表 (Truth Table)
><img src="../assets/images/basic/truth_table.png"  style='width:100%'>

In [73]:
1 + True

2

In [74]:
1 + False

1

In [75]:
True + True*5

6

In [76]:
a = True;  b = False
print(a and b)

False


In [77]:
print(a or b)

True


In [78]:
print(not a)

False


## 1-5 Membership Operators

In [79]:
a = 5;  b = [1, 2, 3, 5, 6]
a in b

True

In [80]:
print(a not in b)

False


## 1-6 Bitwise Operators

><img src="../assets/images/basic/binary01.png"  style='width:90%'>

In [81]:
a = 10;  b = 4
print(f'{a:b}\n{4:4b}')
print(a & b)  # and
print(a | b)  # or
print(a ^ b)  # XOR

1010
 100
0
14
14


In [82]:
a = 10
print(f'{10:b}\n'
      f'{a >> 2}\n'
      f'bin : {a >> 2:b}\n'
      f'{a << 2}\n'
      f'bin : {a << 2:b}') 

1010
2
bin : 10
40
bin : 101000


## 1-7 Integer, float, complex

In [83]:
a = 5; b = 3.1; c = 3.0; d = 1+2j; f = 3.1232e3

print(f'a = {a, type(a)}\n'
      f'b = {b, type(b)}\n'
      f'c = {c, type(c)}\n'
      f'd = {d, type(d)}\n'
      f'f = {f, type(f)}')

a = (5, <class 'int'>)
b = (3.1, <class 'float'>)
c = (3.0, <class 'float'>)
d = ((1+2j), <class 'complex'>)
f = (3123.2, <class 'float'>)


In [84]:
print('int(12.6)\t:', int(12.6))
print('str(12.6)\t:', str(12.6))
print('float(12)\t:', float(12))
print('complex(12)\t:', complex(12))
print('complex(12,3)\t:', complex(12, 3))
str(12.6)

int(12.6)	: 12
str(12.6)	: 12.6
float(12)	: 12.0
complex(12)	: (12+0j)
complex(12,3)	: (12+3j)


'12.6'

## 1-8 Boolean 

In [85]:
print(5 > 3)
print(5 != 3)
print(5 < 3)
print(bool(5%3))
print(bool([]))

True
True
False
True
False


## 1-9 String

><img src="../assets/images/basic/strIndex01.png"  style='width:90%'>

>### 切片 (slice) 格式為 `[起點 : 終點 : 間隔]` 不含`終點`

In [86]:
## this is a string
a = 'hello'
print(a[0], a[1], a[2], a[3], a[4])
print('='*12)
print(a[-1], a[-2], a[-3], a[-4], a[-5])

h e l l o
o l l e h


In [87]:
print(a[2:])
print(a[2::2])
print(a*2)
print(len(a))
print(a[::-1])  # reverse

llo
lo
hellohello
5
olleh


In [88]:
b = 'Python'
print(a+' '+b)

hello Python


In [89]:
l = 'Hello, I am Python!'
print(f'l\t\t\t: {l}')
print(f'upper\t\t\t: {l.upper()}')
print(f'lower\t\t\t: {l.lower()}')
print(f'capitalize\t\t: {l.capitalize()}')
print(f'title\t\t\t: {l.title()}')
print(f'swapcase\t\t: {l.swapcase()}\n')  # upper -> lower,  lower -> upper

print(f'endswith("on!")\t\t: {l.endswith("on!")}')        #True
print(f'startswith("the")\t: {l.startswith("the")}')    #False

l			: Hello, I am Python!
upper			: HELLO, I AM PYTHON!
lower			: hello, i am python!
capitalize		: Hello, i am python!
title			: Hello, I Am Python!
swapcase		: hELLO, i AM pYTHON!

endswith("on!")		: True
startswith("the")	: False


In [90]:
my_string = 'Hello, I am Python!'

print(my_string.split(' '))
print(' '.join(my_string.split(' ')))

['Hello,', 'I', 'am', 'Python!']
Hello, I am Python!


In [91]:
my_string = '   Hello, I am Python!'
print(my_string,'\n', my_string.strip())

   Hello, I am Python! 
 Hello, I am Python!


---

<div style="page-break-after: always"></div>

## 1-10 List 串列

>### `list 與 array 不同`

In [92]:
## this is a list
a = ['apple', 10.4, 1-3j]
b = [1, 3, -2, 8, 9, -10]
print(a[0])
print(a[1])
print(a[-1])
print(b*3)

apple
10.4
(1-3j)
[1, 3, -2, 8, 9, -10, 1, 3, -2, 8, 9, -10, 1, 3, -2, 8, 9, -10]


>### index
><img src="../assets/images/basic/list.png"  style='width:90%'>

>## index, slice

In [93]:
names=['fraser', 'grace', 'john', 'jess', 'jack', 23.5, 2019]
print('names\t\t\t\t=', names)
print('names[0]\t\t\t:', names[0])
print('names[0][0]\t\t\t:', names[0][0], '\n')

print('names[5]\t\t\t:', names[5])
print('names[-1]\t\t\t:', names[-1],'\n')

print('names[1:5]\t\t\t:', names[1:5])
print('names[1:6:2]\t\t\t:', (names[1:6:2]),'\n')

names[2]='Kevin'
print("names[2]='Kevin'\t\t:", names)             # 修改

names[-1:]=[2000, 23.5]                           # 一次改兩筆資料
print('names[-1:]=[2000, 23.5]\t\t:', names)

names				= ['fraser', 'grace', 'john', 'jess', 'jack', 23.5, 2019]
names[0]			: fraser
names[0][0]			: f 

names[5]			: 23.5
names[-1]			: 2019 

names[1:5]			: ['grace', 'john', 'jess', 'jack']
names[1:6:2]			: ['grace', 'jess', 23.5] 

names[2]='Kevin'		: ['fraser', 'grace', 'Kevin', 'jess', 'jack', 23.5, 2019]
names[-1:]=[2000, 23.5]		: ['fraser', 'grace', 'Kevin', 'jess', 'jack', 23.5, 2000, 23.5]


In [94]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [95]:
x, y, z=20, 10, 30
lst=[x, y, z]

print('lst\t\t\t\t=', lst)
print('max(lst)\t\t\t:', max(lst))
print('min(lst)\t\t\t:', min(lst))
print('sum(lst)\t\t\t:', sum(lst))
print('sorted(lst)\t\t\t:', sorted(lst))
print('sorted(lst, reverse=True)\t:', sorted(lst, reverse=True))

lst				= [20, 10, 30]
max(lst)			: 30
min(lst)			: 10
sum(lst)			: 60
sorted(lst)			: [10, 20, 30]
sorted(lst, reverse=True)	: [30, 20, 10]


In [96]:
x = ['apple', 10.4, 1-3j]
y = [1, 3, -2, 8, 9, -10]
y.append(20);     print(y)
y.remove(3);      print(y)
y.pop();          print(y)
y.insert(1, 100); print(y)
y.reverse();      print(y)
y.sort();         print(y)
print(y.count(-2))

[1, 3, -2, 8, 9, -10, 20]
[1, -2, 8, 9, -10, 20]
[1, -2, 8, 9, -10]
[1, 100, -2, 8, 9, -10]
[-10, 9, 8, -2, 100, 1]
[-10, -2, 1, 8, 9, 100]
1


In [97]:
c = [1, 30, -2, -7, 9, -10]
del c[2]
print(c)

[1, 30, -7, 9, -10]


In [98]:
c = ['isaac', 'judy', 'amy']
c_string = ' @ '.join(c)
print(c_string)

isaac @ judy @ amy


## 1-11 Dictionary

In [99]:
a = {'Robert':100, 'judy':60, 'Andy':80}
print(a['Robert'])
print(a.values())
print(a.keys())

100
dict_values([100, 60, 80])
dict_keys(['Robert', 'judy', 'Andy'])


In [100]:
new_key = {'joe':30, 'amy':16, 'Andy':90}   # Andy 80 -> 90
a.update(new_key)
print(a)

{'Robert': 100, 'judy': 60, 'Andy': 90, 'joe': 30, 'amy': 16}


In [101]:
a.pop('amy', None)
print(a)

{'Robert': 100, 'judy': 60, 'Andy': 90, 'joe': 30}


## 1-12 程式的流程控制-條件判斷 if...else

In [102]:
if 0:
    print('True')
else:
    print('False')

False


In [103]:
x = 4
if x == 3:
    print ('x = 3')
else :
    print ('x != 3')

x != 3


In [104]:
# 以下區塊會產生錯誤
if True:
    print('Answer')
    print('True')
else:
    print('Answer')
print('False')

Answer
True
False


In [105]:
s = 60

if s >= 60:
    print('Pass!')
else:
    print('Not pass!')

Pass!


In [106]:
a = 2
if a==1:
    print('a is 1')
print('a is a number')  # 這個 print在 if 之外

a is a number


In [107]:
lst = [11, 22]
lst.clear()  # [], False, [] == False

print('lst\t\t\t= ', lst)  # empty list
print('False == bool(lst))\t:', False == bool(lst))
print('False == bool(None)\t:', False == bool(None))
print('False == 0\t\t:', False == 0)

lst			=  []
False == bool(lst))	: True
False == bool(None)	: True
False == 0		: True


In [108]:
print('False == 0.0\t\t:', False == 0.0)
print('False == bool(())\t:', False == bool(()))  # empty tuple
print('False == bool({})\t:', False == bool({}))  # empty dictionary

False == 0.0		: True
False == bool(())	: True
False == bool({})	: True


In [109]:
a = ()  # same if a :

if a :  # try [], {}, None, False, ''
    print ('True')
else :
    print('None, False')

None, False


In [110]:
var1 =  100
if var1: 
    print('True expr 1 : ', var1) 
print('var1 Finished!')
# -------------------------------    
var2 = 0 
if var2: 
    print('True expr 2 : ', var2) 
    
print('var2 Finished!')

True expr 1 :  100
var1 Finished!
var2 Finished!


### if ... else ...

In [111]:
amt = 900
if amt < 1000:
    discount = amt * 0.05
    print('Discount', discount)
else:
    discount = amt * 0.10
    print('Discount', discount)

Discount 45.0


### if ... elif ... else

In [113]:
amt = int(input('Enter amount: '))

if amt < 1000:
    discount = amt * 0.05
    print('Discount:', discount)
elif amt < 5000:
    discount = amt * 0.10
    print('Discount:', discount)
elif amt < 10000:
    discount = amt * 0.15
    print('Discount:', discount)
else:
    discount = amt * 0.20
    print('Discount:', discount)

print('Net price:', amt - discount)

Discount: 1.0
Net price: 19.0


## 1-13 for loop
> `迭代` :　是程式中對一組指令（或一定步驟）的重複。它既可以被用作通用的術語（與「重複」同義）

In [114]:
for i in [6, 5, 15, 3, 2, 10]:
    print(i)

6
5
15
3
2
10


In [115]:
for i in range(2, 100, 10) :
    print (i)

2
12
22
32
42
52
62
72
82
92


In [116]:
for i in range(1, 10, 2):
    print(f"{'a'*i:^20s}")

         a          
        aaa         
       aaaaa        
      aaaaaaa       
     aaaaaaaaa      


In [117]:
for i in range (1,10):
    if  i < 5 :
        print('if i < 5', i)

if i < 5 1
if i < 5 2
if i < 5 3
if i < 5 4


In [118]:
for i in range(1, 10):
    for j in range(1, 10):
#         print(f'i: {i}, j: {j}')
        print(f'{i:1d}*{j:1d} = {i*j:2d}', end='   ')
    print()

1*1 =  1   1*2 =  2   1*3 =  3   1*4 =  4   1*5 =  5   1*6 =  6   1*7 =  7   1*8 =  8   1*9 =  9   
2*1 =  2   2*2 =  4   2*3 =  6   2*4 =  8   2*5 = 10   2*6 = 12   2*7 = 14   2*8 = 16   2*9 = 18   
3*1 =  3   3*2 =  6   3*3 =  9   3*4 = 12   3*5 = 15   3*6 = 18   3*7 = 21   3*8 = 24   3*9 = 27   
4*1 =  4   4*2 =  8   4*3 = 12   4*4 = 16   4*5 = 20   4*6 = 24   4*7 = 28   4*8 = 32   4*9 = 36   
5*1 =  5   5*2 = 10   5*3 = 15   5*4 = 20   5*5 = 25   5*6 = 30   5*7 = 35   5*8 = 40   5*9 = 45   
6*1 =  6   6*2 = 12   6*3 = 18   6*4 = 24   6*5 = 30   6*6 = 36   6*7 = 42   6*8 = 48   6*9 = 54   
7*1 =  7   7*2 = 14   7*3 = 21   7*4 = 28   7*5 = 35   7*6 = 42   7*7 = 49   7*8 = 56   7*9 = 63   
8*1 =  8   8*2 = 16   8*3 = 24   8*4 = 32   8*5 = 40   8*6 = 48   8*7 = 56   8*8 = 64   8*9 = 72   
9*1 =  9   9*2 = 18   9*3 = 27   9*4 = 36   9*5 = 45   9*6 = 54   9*7 = 63   9*8 = 72   9*9 = 81   


## 1-14 函數 (Function) 設計
> 使用函數 / 函式的好處 :
> * 軟體重複使用
> * 功能切割，模組化，結構化
> * 簡化程式提高程式的可讀性
> * 易於維護及管理
> * 讓程式偵錯更容易

><img src="../assets/images/basic/func.png"  style='width:80%'>

In [119]:
def hi():
    ''' it is a hi() function '''
    print('hi')

# 呼叫 function
hi()

hi


In [120]:
hi?

Signature: hi()
Docstring: it is a hi() function 
File:      /tmp/ipykernel_239496/2708167618.py
Type:      function

In [121]:
# 位置引數
# Function definition
def area(length, width):  # parameter
    return length*width

# Call function
result = area(15, 8)
print('Area =', result)

# result = area(8)  # error. argument missing

Area = 120


In [122]:
# 函式的參數
def fun(s1, s2='world', count=1):
    s = s1+' ' + s2+ '  '
    print(s * count)

fun('Hello')
fun('Hi', 'Jack')
fun('Hi', 'Jack', 2)
fun('Hi', count=3)
fun('Hi', count=3, s2='sky')

Hello world  
Hi Jack  
Hi Jack  Hi Jack  
Hi world  Hi world  Hi world  
Hi sky  Hi sky  Hi sky  


---

<div style="page-break-after: always"></div>

# Mod. 02 NumPy基礎：陣列和向量化計算

> 資料科學（英語：data science）是一門利用資料學習知識的學科，其目標是通過從資料中`提取出有價值的部分`來生產資料產品。它結合了諸多領域中的理論和技術，包括應用`數學、統計、圖型識別、機器學習、資料視覺化、資料倉儲以及高效能計算`。資料科學通過運用各種相關的資料來幫助非專業人士理解問題。 資料科學技術可以幫助我們如何正確的處理資料並協助我們在生物學、社會科學、人類學等領域進行研究調研。此外，資料科學也對商業競爭有極大的幫助。--- wikipedia
<!-- ><img src="./img/stepbystep.jpg"  style='height:550px; width:500px'> -->
><img src="../assets/images/basic/Top10DataScienceSkills.jpeg"  style='width:90%'>

> ndarray (numpy data array) 在儲存數據的時候，數據與數據的地址都是`連續的`，這樣就給使得批次運算元組元素時`速度更快`。

> * ndarray 在儲存元素時記憶體可以連續，而 python 原生 list 就只能通過定址方式找到下一個元素，這雖然也導致了在通用效能方面 Numpy 的 ndarray 不及 Python 原生list，但在科學計算中，Numpy 的 ndarray 就可以`省掉很多回圈語句`，程式碼使用方面比 Python 原生 list 簡單的多。

> * ndarray `支援並行化運算（向量化運算）`numpy 內建了並行運算功能，當系統有多個核心時，做某種計算時，numpy 會自動做`並行計算`

> * 效率遠高於純 Python 程式碼, Numpy 底層使用 C 語言編寫，內部解除了GIL（全域性直譯器鎖），其對陣列的操作速度不受 Python 直譯器的限制，所以，`其效率遠高於純 Python 程式碼`。

><img src="../assets/images/basic/listArray.png"  style='width:90%'>

In [123]:
import numpy as np
import matplotlib.pyplot as plt

## 2-1 多排陣列物件 a Multidimensional Array Object

In [124]:
# Generate some random data
# data = np.random.randn(6)       # (6,) array
data = np.array([[1,2,3], 
                 [4,5,6], [7,8,9]])  # 3*3 array normal distribution
print(f'data =\n{data}\n\n'
      f'type(data) : {type(data)}\n\n'
      f'data * 10 =\n{data*10}\n\n'     # 和 list 不同
      f'data + data =\n {data+data}')  # 和 list [ ] + [ ] 不同

data =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

type(data) : <class 'numpy.ndarray'>

data * 10 =
[[10 20 30]
 [40 50 60]
 [70 80 90]]

data + data =
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Array 1d, 2d ....
><img src="../assets/images/basic/arrays.jpeg"  style='width:90%'>

### shape(4, ) != shape(4, 1)

In [125]:
a = np.array([1,2,3,4])
print(f'a\t\t\t: {a}\n'
      f'a.shape\t\t\t: {a.shape}\n\n'
      f'a.reshape(4,1) :\n{a.reshape(4,1)}\n\n'
      f'.reshape(4,1).shape\t: {a.reshape(4,1).shape}')

a			: [1 2 3 4]
a.shape			: (4,)

a.reshape(4,1) :
[[1]
 [2]
 [3]
 [4]]

.reshape(4,1).shape	: (4, 1)


<div style="page-break-after: always"></div>

## 2-2 NumPy 陣列的基本屬性

|屬性名字	       |屬性解釋                   |
|-----------------|--------------------------|
|ndarray.shape	  |陣列維度的元組             |
|ndarray.ndim	  |陣列維數                   |
|ndarray.size	  |陣列中的元素數量           |
|ndarray.itemsize |一個數組元素的長度（位元組 byte）float64 itemsize值為 8。`等同於ndarray.dtype.itemsize`。|
|ndarray.dtype	  |陣列元素的型別             |

In [126]:
data = np.random.randn(2, 3)  # 2*3 array, normal dist. mu=0, stdev=1
print(f'data =\n{data}\n\n'
      f'data.shape\t: {data.shape}\n'
      f'data.dtype\t: {data.dtype}')

data =
[[-1.44656276 -1.5296413  -0.18923119]
 [ 1.48345131 -1.22080727  0.49225357]]

data.shape	: (2, 3)
data.dtype	: float64


### np.zeros, ones, full, eye ...
> <img src="../assets/images/basic/array_gen.jpg"  style='width:90%'></img>

In [127]:
import numpy as np
arr = np.zeros(10)            # same as arr = np.zeros((10,))
print(f'arr : {arr}\n')

arr = np.zeros((5, 5));    print(f'zeros :\n{arr}\n')
arr = np.ones(5);          print(f'ones :\n{arr}\n') # same as arr = np.ones((10,))
arr = np.ones((5, 5));     print(f'ones :\n{arr}\n')
arr = np.full((5, 5), 7);  print(f'full :\n{arr}\n')

# note : eye, k=0, k=1, k=-1....
arr = np.eye(5, k=-1);     print(f'eye :\n{arr}\n')   # try k=-1, k=2 
arr = np.diag((1,2,3,4,5));  print(f'diag :\n{arr}\n')

arr : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

zeros :
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

ones :
[1. 1. 1. 1. 1.]

ones :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

full :
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]

eye :
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

diag :
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]



<div style="page-break-after: always"></div>

## 2-3 Data Types for ndarrays
|名稱          |描述                                              |簡寫|
|--------------|-------------------------------------------------|----|
|np.bool	   |用一個位元組儲存的布爾型別（True或False）           |'b' |
|np.int8	   |一個位元組大小，-128 至 127	                      |'i' |
|np.int16	   |整數，-32768 至 32767	                          |'i2'|
|`np.int32`    |整數，-2^31​ 至 2^32 -1	                          |'i4'|
|np.int64	   |整數，-2^63 至 2^63 - 1	                          |'i8'|
|`np.uint8`    |無符號整數，0 至 255	                            |'u' |
|np.uint16	   |無符號整數，0 至 65535	                            |'u2'|
|np.uint32	   |無符號整數，0 至 2^32 - 1	                        |'u4'|
|np.uint64	   |無符號整數，0 至 2^64 - 1	                        |'u8'|
|np.float16	   |半精度浮點數：16位元，正負號1位，指數5位，精度10位    |'f2'|
|np.float32    |單精度浮點數：32位元，正負號1位，指數8位元，精度23位  |'f4'|
|`np.float64`  |雙精度浮點數：64位元，正負號1位，指數11位，精度52位   |'f8'|
|np.complex64  |複數，分別用兩個32位元浮點數表示實部和虛部            |'c8'|
|np.complex128 |複數，分別用兩個64位元浮點數表示實部和虛部            |'c16'|
|`np.object_`  |python物件	                                     |'O' |
|np.string_	   |字串	                                             |'S' |
|np.unicode_   |unicode型別                                        |'U' |

---

<div style="page-break-after: always"></div>

# Mod 03 指標和切片 Indexing & Slicing
> Numpy 中多維陣列的切片操作與 Python 中 `list 的切片操作一樣`，同樣由 start, stop, step 三個部分組成

## 3-1 Basic Indexing & Slicing

> ### Illustrate the scope of indexing in NumPy
> <img src="../assets/images/basic/index.jpg"  style='width:90%'></img>

> ### `index : [row, colum]`
> ### `slice : [row : row, column : column, ....]`
> <img src="../assets/images/basic/np_arrays.png"  style='width:90%'></img>
> <img src="../assets/images/basic/index_2d.jpg"  style='width:90%'></img>

In [128]:
import numpy as np
arr = np.arange(10)
print(f'arr\t\t= {arr}\n'
      f'arr[5]\t\t= {arr[5]}\n'
      f'arr[5:8]\t= {arr[5:8]}\n'
      f'arr[5:8:2] \t= {arr[5:8:2]}')

arr[5:8] = 12
print(f'arr\t\t= {arr}')

arr		= [0 1 2 3 4 5 6 7 8 9]
arr[5]		= 5
arr[5:8]	= [5 6 7]
arr[5:8:2] 	= [5 7]
arr		= [ 0  1  2  3  4 12 12 12  8  9]


### axis = 0, axis = 1, axis = ......
> <img src="../assets/images/basic/axis.jpg"  style='width:90%'></img>

> <img src="../assets/images/basic/axis01.jpg"  style='width:90%'></img>

### flatten & ravel

In [129]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'arr2d =\n{arr2d}\n\n'
      f'arr2d[2]\t = {arr2d[2]}\n'
      f'arr2d[0][2]\t = {arr2d[0][2]}\n'
      f'arr2d[0, 2]\t = { arr2d[0, 2]}')

arr2d =
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[2]	 = [7 8 9]
arr2d[0][2]	 = 3
arr2d[0, 2]	 = 3


## 3-2 Indexing with slices
> <img src="../assets/images/basic/np_indexing.png"  style='width:90%'></img>

In [130]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d, arr2d[:2]  # row only

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [131]:
arr2d[:2, 1:]  # row and column

array([[2, 3],
       [5, 6]])

In [132]:
arr2d[1, :2]

array([4, 5])

In [133]:
arr2d[:2, 2:]

array([[3],
       [6]])

In [134]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [135]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [136]:
arr = np.arange(15).reshape((3, 5))
arr, arr.T, np.transpose(arr)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]))

In [137]:
arr = np.arange(15).reshape((3, 5))
arr, arr.swapaxes(0, 1), arr.T

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]))

In [138]:
arr = np.arange(16).reshape((2,2,4))
arr, arr.transpose((1,2,0)), arr.shape, arr.transpose((1,2,0)).shape # (1,2,0) are indexes

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]]),
 array([[[ 0,  8],
         [ 1,  9],
         [ 2, 10],
         [ 3, 11]],
 
        [[ 4, 12],
         [ 5, 13],
         [ 6, 14],
         [ 7, 15]]]),
 (2, 2, 4),
 (2, 4, 2))

---
<center><h1>--- The End ---</h1></center>